services:
  agent-zero-run:
    image: agent-zero-run
    restart: unless-stopped
    # env_file:
    #  - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BRANCH=main
    volumes:
      - ../../prompts:/a0/prompts
      - ../../knowledge:/a0/knowledge
      - ../../memory:/a0/memory
      - ../../tmp:/a0/tmp
      - ../../work_dir:/a0/work_dir
      - ./fs/etc/supervisor/conf.d/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    working_dir: /a0
    tty: true
    # env_file:
    #   - ../../.env